# Generated by Django 4.2.7 on 2023-12-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('receiver', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.emailtemplate')),
            ],
        ),
    ]
